### PR TITLE
allow specification of timeouts

### PR DESCRIPTION
**Pull request by gjesse**
We'd like to be able to set a shorter session timeout

### CODE REVIEW

**Comment by ohhatiya** [comment]
Ok to test

**Comment by ohhatiya** [comment]
Jenkins, test this please

**Comment by ohhatiya** [comment]
Jenkins, ok to test

**Comment by ohhatiya** [comment]
Awesome, thanks! Will do a release shortly.

**Comment by gjesse** [comment]
sweet, thanks!

**Pull request merged**
